export const AboutData = {
    
        Heading:"About PCSIR Labs Complex ",
        p1:"Pakistan Council of Scientific and Industrial Research (PCSIR) was established in 1953 under Societies Act to promote the cause of Science and Technology in the country. Since 1973, it is functioning under the Act of Parliament, which was amended in 1984. Chief Executive of the Council is the Chairman who is appointed by the Federal Government.",
        p2:"The 21- member Council is the policy making body of the PCSIR, which is composed of Chairman, three Members of the Governing Body, three Directors of PCSIR Laboratories, four representatives from four ministries, four Directors of Industries, one from each province and six representatives of the industry.",
        p3:"The Governing Body is the executive organ of the Council and comprises of the Chairman and three full-time members viz Member (Science), Member (Technology)  and Member (Finance), nominated by the Government. The Head Office of the PCSIR is functioning at Islamabad where offices of the Chairman, Member (Science), Member (Technology), Member (Finance) and Secretary PCSIR are located.",
        p4:"The Science Wing is headed by Member (Science), who supervises matters relating to R&D, Training, International Affairs and Scientific Information Services.The Technology Wing is headed by the Member (Technology), who looks after the matters relating to Technology, Industrial Liaison and Civil Works.",
        p5:"The Finance Wing is headed by the Member (Finance) who is in charge of activities in Finance and Audit and Accounts Divisions. The Chairman is assisted by the Secretary and Administration and Establishment Wings, working directly under him.There are eleven Laboratories / Units and five HRD Centers established throughout the country, headed by Director Generals / Directors who directly report to the Chairman. In Head Office 150 officers / staff including 07 Directors are working in different divisions / wings. There are 570 Scientists / Engineers / Technologists working in different Laboratories supported by 859 technicians/skilled workers/supporting staff and 1125 non-technical (administrative/ accounts / security etc.) staff."
    
}